{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ab954868-cb1e-4684-8229-a42eaac4e6e0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please select the GSTR-2B and GSTR-2A files.\n",
      "Columns in merged DataFrame:\n",
      "['GSTIN of supplier', 'Trade/Legal name', 'Invoice number', 'Invoice type', 'Invoice Date', 'Invoice Value(₹)', 'Place of supply', 'Supply Attract Reverse Charge', 'Rate(%)_x', 'Taxable Value (₹)_x', 'Integrated Tax(₹)_x', 'Central Tax(₹)_x', 'State/UT Tax(₹)_x', 'Cess(₹)_x', 'GSTR-1/5 Period', 'GSTR-1/5 Filing Date', 'ITC Availability', 'Reason', 'Applicable % of Tax Rate', 'Source', 'IRN', 'IRN Date', 'Period', 'Rate(%)_y', 'Taxable Value (₹)_y', 'Integrated Tax(₹)_y', 'Central Tax(₹)_y', 'State/UT Tax(₹)_y', 'Cess(₹)_y']\n",
      "Merged file saved as a table to D:/OneDrive/Office-One Drive/Client Excel/Adinn Reco/Python Output.xlsx\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import openpyxl\n",
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "\n",
    "# Function to load the Excel files\n",
    "def load_excel_files():\n",
    "    root = tk.Tk()\n",
    "    root.withdraw()\n",
    "    gstr2b_path = filedialog.askopenfilename(title=\"Select GSTR-2B Excel File\", filetypes=[(\"Excel Files\", \"*.xlsx\")])\n",
    "    gstr2a_path = filedialog.askopenfilename(title=\"Select GSTR-2A Excel File\", filetypes=[(\"Excel Files\", \"*.xlsx\")])\n",
    "    return gstr2b_path, gstr2a_path\n",
    "\n",
    "# Function to process and merge the files\n",
    "def process_and_merge(gstr2b_path, gstr2a_path, output_path):\n",
    "    # Load the data from both files\n",
    "    gstr2b = pd.read_excel(gstr2b_path, sheet_name=\"B2B\", header=None, skiprows=6)\n",
    "    gstr2a = pd.read_excel(gstr2a_path, sheet_name=\"B2B\", header=None, skiprows=6)\n",
    "\n",
    "    # Define the column headers for GSTR-2B and GSTR-2A\n",
    "    gstr2b_columns = [\n",
    "        \"GSTIN of supplier\", \"Trade/Legal name\", \"Invoice number\", \"Invoice type\",\n",
    "        \"Invoice Date\", \"Invoice Value(₹)\", \"Place of supply\", \"Supply Attract Reverse Charge\",\n",
    "        \"Rate(%)\", \"Taxable Value (₹)\", \"Integrated Tax(₹)\", \"Central Tax(₹)\",\n",
    "        \"State/UT Tax(₹)\", \"Cess(₹)\", \"GSTR-1/5 Period\", \"GSTR-1/5 Filing Date\",\n",
    "        \"ITC Availability\", \"Reason\", \"Applicable % of Tax Rate\", \"Source\", \"IRN\",\n",
    "        \"IRN Date\", \"Period\"\n",
    "    ]\n",
    "\n",
    "    gstr2a_columns = [\n",
    "        \"GSTIN of supplier\", \"Trade/Legal name of the Supplier\", \"Invoice number\", \"Invoice type\",\n",
    "        \"Invoice Date\", \"Invoice Value (₹)\", \"Place of supply\", \"Supply Attract Reverse Charge\",\n",
    "        \"Rate (%)\", \"Taxable Value (₹)\", \"Integrated Tax  (₹)\", \"Central Tax (₹)\",\n",
    "        \"State/UT tax (₹)\", \"Cess  (₹)\", \"GSTR-1/5 Filing Status\", \"GSTR-1/5 Filing Date\",\n",
    "        \"GSTR-1/5 Filing Period\", \"GSTR-3B Filing Status\", \"Amendment made, if any\",\n",
    "        \"Tax Period in which Amended\", \"Effective date of cancellation\", \"Period\"\n",
    "    ]\n",
    "\n",
    "    # Assign column headers to the dataframes\n",
    "    gstr2b.columns = gstr2b_columns\n",
    "    gstr2a.columns = gstr2a_columns\n",
    "\n",
    "    # Rename columns for consistent merging\n",
    "    gstr2a.rename(columns={\n",
    "        \"Trade/Legal name of the Supplier\": \"Trade/Legal name\",\n",
    "        \"Rate (%)\": \"Rate(%)\",\n",
    "        \"Taxable Value (₹)\": \"Taxable Value (₹)\",\n",
    "        \"Integrated Tax  (₹)\": \"Integrated Tax(₹)\",\n",
    "        \"Central Tax (₹)\": \"Central Tax(₹)\",\n",
    "        \"State/UT tax (₹)\": \"State/UT Tax(₹)\",\n",
    "        \"Cess  (₹)\": \"Cess(₹)\"\n",
    "    }, inplace=True)\n",
    "\n",
    "    # Merge using \"Invoice number\" and \"GSTIN of supplier\"\n",
    "    merged = pd.merge(\n",
    "        gstr2b, gstr2a[\n",
    "            [\"Invoice number\", \"GSTIN of supplier\", \"Rate(%)\", \"Taxable Value (₹)\", \"Integrated Tax(₹)\", \"Central Tax(₹)\", \"State/UT Tax(₹)\", \"Cess(₹)\"]\n",
    "        ],\n",
    "        on=[\"Invoice number\", \"GSTIN of supplier\"],\n",
    "        how=\"left\"\n",
    "    )\n",
    "\n",
    "    # Debugging: Print the columns of the merged DataFrame\n",
    "    print(\"Columns in merged DataFrame:\")\n",
    "    print(merged.columns.tolist())\n",
    "\n",
    "    # Remove specified columns from GSTR-2B and GSTR-2A if they exist\n",
    "    columns_to_remove = [\"Rate(%)_x\", \"Taxable Value (₹)_x\", \"Integrated Tax(₹)_x\", \"Central Tax(₹)_x\", \"State/UT Tax(₹)_x\", \"Cess(₹)_x\"]\n",
    "    columns_to_remove = [col for col in columns_to_remove if col in merged.columns]\n",
    "    merged.drop(columns=columns_to_remove, inplace=True)\n",
    "\n",
    "    # Reorder columns to insert Rate(%)_y, Taxable Value (₹)_y, etc., after \"Supply Attract Reverse Charge\"\n",
    "    insertion_columns = [\"Rate(%)_y\", \"Taxable Value (₹)_y\", \"Integrated Tax(₹)_y\", \"Central Tax(₹)_y\", \"State/UT Tax(₹)_y\", \"Cess(₹)_y\"]\n",
    "    main_columns = merged.columns.tolist()\n",
    "    position = main_columns.index(\"Supply Attract Reverse Charge\") + 1\n",
    "    for col in reversed(insertion_columns):\n",
    "        if col in main_columns:\n",
    "            main_columns.remove(col)\n",
    "        main_columns.insert(position, col)\n",
    "\n",
    "    merged = merged[main_columns]\n",
    "\n",
    "    # Export the merged file as a table in Excel\n",
    "    with pd.ExcelWriter(output_path, engine=\"openpyxl\") as writer:\n",
    "        merged.to_excel(writer, index=False, sheet_name=\"Merged Data\")\n",
    "        workbook = writer.book\n",
    "        worksheet = writer.sheets[\"Merged Data\"]\n",
    "\n",
    "        # Create an Excel table\n",
    "        from openpyxl.utils import get_column_letter\n",
    "        from openpyxl.worksheet.table import Table, TableStyleInfo\n",
    "        last_column = get_column_letter(merged.shape[1])\n",
    "        tab = Table(displayName=\"MergedTable\", ref=f\"A1:{last_column}{merged.shape[0] + 1}\")\n",
    "        style = TableStyleInfo(\n",
    "            name=\"TableStyleMedium9\", showFirstColumn=False, showLastColumn=False,\n",
    "            showRowStripes=True, showColumnStripes=True\n",
    "        )\n",
    "        tab.tableStyleInfo = style\n",
    "        worksheet.add_table(tab)\n",
    "\n",
    "        # Autofit columns\n",
    "        for column_cells in worksheet.columns:\n",
    "            max_length = 0\n",
    "            column = column_cells[0].column_letter\n",
    "            for cell in column_cells:\n",
    "                try:  # Necessary to handle empty cells\n",
    "                    if cell.value:\n",
    "                        max_length = max(max_length, len(str(cell.value)))\n",
    "                except:\n",
    "                    pass\n",
    "            adjusted_width = (max_length + 2)\n",
    "            worksheet.column_dimensions[column].width = adjusted_width\n",
    "\n",
    "    print(f\"Merged file saved as a table to {output_path}\")\n",
    "\n",
    "# Main execution\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"Please select the GSTR-2B and GSTR-2A files.\")\n",
    "    gstr2b_path, gstr2a_path = load_excel_files()\n",
    "    output_path = filedialog.asksaveasfilename(\n",
    "        title=\"Save Merged File As\", defaultextension=\".xlsx\", filetypes=[(\"Excel Files\", \"*.xlsx\")]\n",
    "    )\n",
    "\n",
    "    if gstr2b_path and gstr2a_path and output_path:\n",
    "        process_and_merge(gstr2b_path, gstr2a_path, output_path)\n",
    "    else:\n",
    "        print(\"Operation cancelled.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c47bb403-5839-4a8c-a1fe-6da3fe702663",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
